name: Example - Use Composite Action build-push

on:
  push:
    branches: [ main ]
    paths: ['**']

jobs:
  build-in-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build-push composite
        uses: PookieLand/workflows_hrms/.github/actions/build-push@main
        with:
          servicePath: '.'
          imageName: 'hrms/example-service'
          registry: '475936984863.dkr.ecr.ap-south-1.amazonaws.com'
          region: 'ap-south-1'
          push_image: false
