name: Example - Call Reusable Build and Push

on:
  workflow_dispatch: {}

jobs:
  build-and-push:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      servicePath: '.'
      imageName: 'hrms/example-service'
      registry: '475936984863.dkr.ecr.ap-south-1.amazonaws.com'
      region: 'ap-south-1'
      push_image: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
